// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://essjgvzyseoqfekcdjth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzc2pndnp5c2VvcWZla2NkanRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MjUwODYsImV4cCI6MjA3MTIwMTA4Nn0._cOzTZ3nGuomAfUQjb27P4DGFrHTIt9f5m60VWH3ENU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});